# Name of the image to build/container to run.
# This results in an image named identidock_identidock and in a container named identidock_identidock_1. 
identidock:
  # For building the image:
  # Build the image for that container from a Dockerfile that can be found in the given directory.
  build: .
  
  # For running the container:
  # Equivalent to docker container run ... -p 5000:5000.
  ports:
    - "5000:5000"
  # Equal to docker container run -e. Sets the environment variable ENV to DEV.  
  environment:
    ENV: DEV
  # Equal to docker container run -v ... .
  # Bind mount the directory app into the container.     
  volumes:
    - ./app:/app
  # Link the given containers into this container.
  # Compose calculates the order to start the container,    
  links:
    - dnmonster
    - redis


# Name of the next image/container to run.
# Here the image is downloaded from the Docker Hub and then run in a container that is based on that image.    
dnmonster:
  image: amouat/dnmonster:1.0
  
# Use a Redis-container to enable caching for the identicons
redis:
  image: redis:3.0